# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170623_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bookName',
            new_name='book_name',
        ),
    ]
