# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170623_0149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title', 'published_date']},
        ),
    ]
