# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_author_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(help_text='e.x fakeemail@gmail.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, choices=[('d', 'N/A'), ('A', 'ACT Test Prep'), ('G', 'Study Guide'), ('P', 'AP Test Prep'), ('S', 'SAT Test Prep'), ('T', 'Textbook'), ('W', 'Workbook')], default='d', help_text='Select a Genre, do not leave blank', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.CharField(default='e.x 111-111-1111', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(default='e.x $3.00', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.CharField(default='e.x 1999', max_length=255, null=True),
        ),
    ]
