# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170626_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('ACT_Test_Prep', 'ACT Test Prep'), ('Study_Guide', 'Study Guide'), ('AP_Test_Prep', 'AP Test Prep'), ('SAT_Test_Prep', 'SAT Test Prep'), ('Textbook', 'Textbook'), ('Workbook', 'Workbook')], default='N/A', help_text='Select a Genre, do not leave blank', max_length=1),
        ),
    ]
