# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170626_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, choices=[('d', 'N/A'), ('a', 'ACT Test Prep'), ('b', 'Study Guide'), ('c', 'AP Test Prep'), ('d', 'SAT Test Prep'), ('f', 'Textbook'), ('g', 'Workbook')], default='d', help_text='Select a Genre, do not leave blank', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(help_text='e.x 3.00', max_length=255, null=True),
        ),
    ]
