# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170627_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(help_text='e.x 3.00, leave out the dollar sign', max_length=255, null=True),
        ),
    ]
