# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20171226_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_attribute', models.CharField(blank=True, choices=[('d', 'N/A'), ('a', 'Title'), ('b', 'Seller'), ('c', 'Book_Type'), ('e', 'Academic_Subject')], default='d', help_text='Select a search type, do not leave blank', max_length=1)),
                ('search_field', models.CharField(help_text='e.x Biology', max_length=255, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_date', 'published_date'],
            },
        ),
    ]
